CREATE TABLE quantity_measurements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value1        DOUBLE PRECISION,
    unit1         VARCHAR(255),
    type          VARCHAR(255),
    value2        DOUBLE PRECISION,
    unit2         VARCHAR(255),
    operation     VARCHAR(255),
    result        DOUBLE PRECISION,
    result_unit   VARCHAR(255),
    error         BOOLEAN                                 NOT NULL,
    error_message VARCHAR(255),
    CONSTRAINT pk_quantity_measurements PRIMARY KEY (id)
);