# =======================
# APPLICATION NAME
# =======================
spring.application.name=quantity-measurement-app


# =======================
# MYSQL DATABASE CONFIGURATION
# =======================

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

#spring.datasource.url=jdbc:mysql://localhost:3306/quantity_db_hritik
#spring.datasource.username=
#spring.datasource.password=


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =======================
# JPA / HIBERNATE
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =======================
# SWAGGER (OpenAPI) CONFIGURATION
# =======================

springdoc.swagger-ui.path=/quantity-measurement-app


# =======================
# SPRING BOOT ACTUATOR CONFIGURATION
# =======================

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always


# =======================
# JWT CONFIG
# =======================

jwt.secret=HritikChauhanSuperSecretKey@2026#SecureJWTKey
jwt.expiration=86400000


# ===============================
# ? GOOGLE OAUTH2 CONFIG
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile
# Must match an "Authorized redirect URI" in Google Cloud Console exactly.

# Use Railway public URL in production; override via env var for other environments.

spring.security.oauth2.client.registration.google.redirect-uri=https://quantitymeasurementapp-production-c4e6.up.railway.app/login/oauth2/code/google


# ===============================
# FRONTEND URLs (React) deploy
# ===============================
app.oauth2.frontend-redirect=https://quantity-measurement-app-frontend-red.vercel.app/auth/callback
app.oauth2.frontend-login-url=https://quantity-measurement-app-frontend-red.vercel.app/login

#app.oauth2.frontend-redirect=http://localhost:5173/auth/callback
#app.oauth2.frontend-login-url=http://localhost:5173/login
